name: Deploy infrastructure

on:
  push:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  SERVER_DEPLOY_DIR: ~/politgraph/

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit