name: Docker - politgraph.ui

on:
  push:
    branches: [ "main" ]
    paths:
      - "politgraph.ui/**"
      - ".github/workflows/docker_build.yml"
      - ".github/workflows/deploy_infra.yml"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/publish_ui.yml"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
    paths:
      - "politgraph.ui/**"

jobs:
  docker:
    uses: ./.github/workflows/docker_build.yml
    with:
      dockerfile: politgraph.ui/Dockerfile
    secrets: inherit
