name: Docker - politgraph.py

on:
  push:
    branches: [ "main" ]
    paths:
      - "politgraph.py/**"
      - ".github/workflows/docker_build.yml"
      - ".github/workflows/deploy_infra.yml"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/publish_py.yml"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
    paths:
      - "politgraph.py/**"

jobs:
  docker:
    uses: ./.github/workflows/docker_build.yml
    with:
      dockerfile: politgraph.py/Dockerfile
      context: ./politgraph.py/
      image_name: "politgraph-update"
    secrets: inherit
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
